# Импорт библиотек

In [104]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

# EDA

In [105]:
df = pd.read_excel('data/result2022.xlsx')

In [106]:
df.head()

,"Средний балл ЕГЭ студентов, принятых по результатам ЕГЭ на обучение по очной форме по программам бакалавриата и специалитета за счет средств соответствующих бюджетов бюджетной системы РФ","Средний балл ЕГЭ студентов университета, принятых по результатам ЕГЭ на обучение по очной форме по программам бакалавриата и специалитета за счет средств соответствующих бюджетов бюджетной системы Российской Федерации, за исключением лиц, поступивших с учетом особых прав и в рамках квоты целевого приема","Средний балл ЕГЭ студентов, принятых по результатам ЕГЭ на обучение по очной форме по программам бакалавриата и специалитета с оплатой стоимости затрат на обучение физическими и юридическими лицами","Усредненный по реализуемым направлениям (специальностям) минимальный балл ЕГЭ студентов, принятых по результатам ЕГЭ на обучение по очной форме на программы бакалавриата и специалитета","Численность студентов, победителей и призеров заключительного этапа всероссийской олимпиады школьников, членов сборных команд Российской Федерации, участвовавших в международных олимпиадах по общеобразовательным предметам по специальностям и (или) направлениям подготовки, соответствующим профилю всероссийской олимпиады школьников или международной олимпиады, принятых на очную форму обучения на первый курс по программам бакалавриата и специалитета без вступительных испытаний","Численность студентов, победителей и призеров олимпиад школьников, принятых на очную форму обучения на первый курс по программам бакалавриата и специалитета по специальностям и (или) направлениям подготовки, соответствующим профилю олимпиады школьников, без вступительных испытаний","Численность студентов, принятых по результатам целевого приема на первый курс на очную форму обучения по программам бакалавриата и специалитета","Удельный вес численности студентов, принятых по результатам целевого приема на первый курс на очную форму обучения по программам бакалавриата и специалитета в общей численности студентов, принятых на первый курс по программам бакалавриата и специалитета на очную форму обучения","Удельный вес численности студентов (приведенного контингента), обучающихся по программам магистратуры, в общей численности приведенного контингента обучающихся по образовательным программам бакалавриата, специалитета и магистратуры","Удельный вес численности обучающихся (приведенного контингента), по программам магистратуры, подготовки научно-педагогических кадров в аспирантуре (адъюнктуре), ординатуры, ассистентуры-стажировки в общей численности приведенного контингента обучающихся по основным образовательным программам высшего образования",...,Доля доходов вуза от образовательной деятельности в общих доходах вуза,Доля доходов вуза от научных исследований и разработок в общих доходах вуза,Доля внебюджетных средств в доходах от образовательной деятельности,Доля внебюджетных средств в доходах от научных исследований и разработок,VUZ,Region,Type,Site,ID,year
0,0.00,0.00,61.28,48.28,0,0,0,0.0,8.34,8.34,...,80.76,4.42,100.00,100.00,Автономная некоммерческая образовательная орга...,Воронежская область,Частные образовательные организации,http://www.vepi.ru,110170,2022
1,51.69,51.69,51.48,39.26,0,0,0,0.0,0.00,0.00,...,66.01,11.19,34.13,100.00,Автономная некоммерческая образовательная орга...,Воронежская область,Частные образовательные организации,http://www.iict.ru,1996,2022
2,0.00,0.00,0.00,0.00,0,0,0,0.0,0.00,0.00,...,97.58,0.00,100.00,0.00,Автономная некоммерческая образовательная орга...,Курская область,Частные образовательные организации,http://rfei.ru/,2071,2022
3,0.00,0.00,55.70,55.70,0,0,0,0.0,0.00,0.00,...,68.66,1.53,100.00,100.00,Автономная некоммерческая образовательная орга...,Московская область,Частные образовательные организации,https://www.pssi-k.ru/,666667486,2022
4,0.00,0.00,0.00,0.00,0,0,0,0.0,100.00,100.00,...,9.09,85.08,9.77,12.17,Автономная некоммерческая образовательная орга...,г.Москва,Частные образовательные организации,www.skoltech.ru,113493,2022

Посмотрим размер датасета

In [107]:
df.shape

(681, 133)

Быстрый обзор типов/пропусков

In [108]:
df.dtypes.head(30)

Средний балл ЕГЭ студентов, принятых по результатам ЕГЭ на обучение по очной форме по программам бакалавриата и специалитета за счет средств соответствующих бюджетов бюджетной системы РФ                                                                                                                                                                                                                                                                                                        float64
Средний балл ЕГЭ студентов университета, принятых по результатам ЕГЭ на обучение по очной форме по программам бакалавриата и специалитета за счет средств соответствующих бюджетов бюджетной системы Российской Федерации, за исключением лиц, поступивших с учетом особых прав и в рамках квоты целевого приема                                                                                                                                                                                  float64
Средний балл ЕГЭ студентов, принятых по результатам ЕГЭ на обучение по очной форме по программам бакалавриата и специалитета с оплатой стоимости затрат на обучение физическими и юридическими лицами                                                                                                                                                                                                                                                                                             float64
Усредненный по реализуемым направлениям (специальностям) минимальный балл ЕГЭ студентов, принятых по результатам ЕГЭ на обучение по очной форме на программы бакалавриата и специалитета                                                                                                                                                                                                                                                                                                          float64
Численность студентов, победителей и призеров заключительного этапа всероссийской олимпиады школьников, членов сборных команд Российской Федерации, участвовавших в международных олимпиадах по общеобразовательным предметам по специальностям и (или) направлениям подготовки, соответствующим профилю всероссийской олимпиады школьников или международной олимпиады, принятых на очную форму обучения на первый курс по программам бакалавриата и специалитета без вступительных испытаний      int64
Численность студентов, победителей и призеров олимпиад школьников, принятых на очную форму обучения на первый курс по программам бакалавриата и специалитета по специальностям и (или) направлениям подготовки, соответствующим профилю олимпиады школьников, без вступительных испытаний                                                                                                                                                                                                           int64
Численность студентов, принятых по результатам целевого приема на первый курс на очную форму обучения по программам бакалавриата и специалитета                                                                                                                                                                                                                                                                                                                                                     int64
Удельный вес численности студентов, принятых по результатам целевого приема на первый курс на очную форму обучения по программам бакалавриата и специалитета в общей численности студентов, принятых на первый курс по программам бакалавриата и специалитета на очную форму обучения                                                                                                                                                                                                             float64
Удельный вес численности студентов (приведенного контингента), обучающихся по программам магистратуры, в общей численности приведенного контингента обучающихся по образовательным программам бакалавриата, специалитета и магистратуры                                                                                                                                                                                                                                                           float64
Удельный вес численности обучающихся (приведенного контингента), по программам магистратуры, подготовки научно-педагогических кадров в аспирантуре (адъюнктуре), ординатуры, ассистентуры-стажировки в общей численности приведенного контингента обучающихся по основным образовательным программам высшего образования                                                                                                                                                                          float64
Удельный вес численности студентов, имеющих диплом бакалавра, специалиста или магистра других организаций, принятых на первый курс на обучение по программам магистратуры образовательной организации, в общей численности студентов, принятых на первый курс по программам магистратуры на очную форму обучения                                                                                                                                                                                  float64
Удельный вес численности обучающихся по программам магистратуры, подготовки научно-педагогических кадров в аспирантуре (адъюнктуре), ординатуры, ассистентуры-стажировки, имеющих диплом бакалавра, диплом специалиста или диплом магистра других организаций в общей численности обучающихся по программам магистратуры, подготовки научно-педагогических кадров в аспирантуре (адъюнктуре), ординатуры, ассистентуры-стажировки                                                                 float64
Численность аспирантов (адъюнктов), ординаторов, ассистентов-стажеров образовательной организации в расчете на 100 студентов (приведенного контингента)                                                                                                                                                                                                                                                                                                                                           float64
Удельный вес численности слушателей из сторонних организаций в общей численности слушателей, прошедших обучение в образовательной организации по программам повышения квалификации или профессиональной переподготовки                                                                                                                                                                                                                                                                            float64
Удельный вес численности студентов, обучающихся по направлениям подготовки бакалавриата, специалитета, и магистратуры по областям знаний «Инженерное дело, технологии и технические науки», «Здравоохранение и медицинские науки», «Образование и педагогические науки», с которыми заключены договоры о целевом обучении, в общей численности студентов, обучающихся по указанным областям знаний                                                                                                float64
Количество цитирований публикаций, изданных за последние 5 лет, индексируемых в информационно-аналитической системе научного цитирования Web of Science Core Collection в расчете на 100 НПР[н]                                                                                                                                                                                                                                                                                                   float64
Количество цитирований публикаций, изданных за последние 5 лет, индексируемых в информационно-аналитической системе научного цитирования Scopus в расчете на 100 НПР[н]                                                                                                                                                                                                                                                                                                                           float64
Количество цитирований публикаций, изданных за последние 5 лет, индексируемых в Российском индексе научного цитирования (далее – РИНЦ) в расчете на 100 НПР[н]                                                                                                                                                                                                                                                                                                                                    float64
Число публикаций организации, индексируемых в информационно-аналитической системе научного цитирования Web of Science Core Collection, в расчете на 100 НПР[н]                                                                                                                                                                                                                                                                                                                                    float64
Число публикаций организации, индексируемых в информационно-аналитической системе научного цитирования Scopus, в расчете на 100 НПР[н]                                                                                                                                                                                                                                                                                                                                                            float64
Число публикаций организации, индексируемых в информационно-аналитической системе научного цитирования РИНЦ, в расчете на 100 НПР[н]                                                                                                                                                                                                                                                                                                                                                              float64
Общий объем научно-исследовательских и опытно-конструкторских работ (далее – НИОКР)                                                                                                                                                                                                                                                                                                                                                                                                               float64
Удельный вес доходов от НИОКР в общих доходах образовательной организации                                                                                                                                                                                                                                                                                                                                                                                                                         float64
Удельный вес НИОКР, выполненных собственными силами (без привлечения соисполнителей), в общих доходах образовательной организации от НИОКР                                                                                                                                                                                                                                                                                                                                                        float64
Доходы от НИОКР (за исключением средств бюджетов бюджетной системы Российской Федерации, государственных фондов поддержки науки) в расчете на одного НПР[н]                                                                                                                                                                                                                                                                                                                                       float64
Количество лицензионных соглашений                                                                                                                                                                                                                                                                                                                                                                                                                                                                  int64
Удельный вес средств, полученных образовательной организацией от использования результатов интеллектуальной деятельности, в общих доходах образовательной организации                                                                                                                                                                                                                                                                                                                             float64
Удельный вес численности НПР без ученой степени – до 30 лет, кандидатов наук – до 35 лет, докторов наук – до 40 лет, в общей численности НПР[н]                                                                                                                                                                                                                                                                                                                                                   float64
Удельный вес научно-педагогических работников, защитивших кандидатские и докторские диссертации за отчетный период в общей численности НПР                                                                                                                                                                                                                                                                                                                                                        float64
Количество научных журналов, в том числе электронных, издаваемых образовательной организацией                                                                                                                                                                                                                                                                                                                                                                                                       int64
dtype: object

Нужна нормализация названия столбцов, произведем ее

In [109]:
col_rename = {
    "Средний балл ЕГЭ студентов, принятых по результатам ЕГЭ на обучение по очной форме по программам бакалавриата и специалитета за счет средств соответствующих бюджетов бюджетной системы РФ": "ege_avg_budget_full_time",
    "Средний балл ЕГЭ студентов университета, принятых по результатам ЕГЭ на обучение по очной форме по программам бакалавриата и специалитета за счет средств соответствующих бюджетов бюджетной системы Российской Федерации, за исключением лиц, поступивших с учетом особых прав и в рамках квоты целевого приема": "ege_avg_budget_full_time_no_special_rights_no_target_quota",
    "Средний балл ЕГЭ студентов, принятых по результатам ЕГЭ на обучение по очной форме по программам бакалавриата и специалитета с оплатой стоимости затрат на обучение физическими и юридическими лицами": "ege_avg_paid_full_time",
    "Усредненный по реализуемым направлениям (специальностям) минимальный балл ЕГЭ студентов, принятых по результатам ЕГЭ на обучение по очной форме на программы бакалавриата и специалитета": "ege_min_avg_full_time",
    "Численность студентов, победителей и призеров заключительного этапа всероссийской олимпиады школьников, членов сборных команд Российской Федерации, участвовавших в международных олимпиадах по общеобразовательным предметам по специальностям и (или) направлениям подготовки, соответствующим профилю всероссийской олимпиады школьников или международной олимпиады, принятых на очную форму обучения на первый курс по программам бакалавриата и специалитета без вступительных испытаний": "olympiad_final_winners_admitted_no_exams",
    "Численность студентов, победителей и призеров олимпиад школьников, принятых на очную форму обучения на первый курс по программам бакалавриата и специалитета по специальностям и (или) направлениям подготовки, соответствующим профилю олимпиады школьников, без вступительных испытаний": "school_olympiad_winners_admitted_no_exams",
    "Численность студентов, принятых по результатам целевого приема на первый курс на очную форму обучения по программам бакалавриата и специалитета": "target_admission_count_full_time",
    "Удельный вес численности студентов, принятых по результатам целевого приема на первый курс на очную форму обучения по программам бакалавриата и специалитета в общей численности студентов, принятых на первый курс по программам бакалавриата и специалитета на очную форму обучения": "target_admission_share_full_time",
    "Удельный вес численности студентов (приведенного контингента), обучающихся по программам магистратуры, в общей численности приведенного контингента обучающихся по образовательным программам бакалавриата, специалитета и магистратуры": "masters_share_in_total_contingent",
    "Удельный вес численности обучающихся (приведенного контингента), по программам магистратуры, подготовки научно-педагогических кадров в аспирантуре (адъюнктуре), ординатуры, ассистентуры-стажировки в общей численности приведенного контингента обучающихся по основным образовательным программам высшего образования": "postgrad_and_residency_share_in_total_contingent",
    "Удельный вес численности студентов, имеющих диплом бакалавра, специалиста или магистра других организаций, принятых на первый курс на обучение по программам магистратуры образовательной организации, в общей численности студентов, принятых на первый курс по программам магистратуры на очную форму обучения": "masters_admitted_from_other_orgs_share_full_time",
    "Удельный вес численности обучающихся по программам магистратуры, подготовки научно-педагогических кадров в аспирантуре (адъюнктуре), ординатуры, ассистентуры-стажировки, имеющих диплом бакалавра, диплом специалиста или диплом магистра других организаций в общей численности обучающихся по программам магистратуры, подготовки научно-педагогических кадров в аспирантуре (адъюнктуре), ординатуры, ассистентуры-стажировки": "postgrad_from_other_orgs_share",
    "Численность аспирантов (адъюнктов), ординаторов, ассистентов-стажеров образовательной организации в расчете на 100 студентов (приведенного контингента)": "postgrad_per_100_students",
    "Удельный вес численности слушателей из сторонних организаций в общей численности слушателей, прошедших обучение в образовательной организации по программам повышения квалификации или профессиональной переподготовки": "dpo_external_listeners_share",
    "Удельный вес численности студентов, обучающихся по направлениям подготовки бакалавриата, специалитета, и магистратуры по областям знаний «Инженерное дело, технологии и технические науки», «Здравоохранение и медицинские науки», «Образование и педагогические науки», с которыми заключены договоры о целевом обучении, в общей численности студентов, обучающихся по указанным областям знаний": "target_contract_share_priority_fields",

    "Количество цитирований публикаций, изданных за последние 5 лет, индексируемых в информационно-аналитической системе научного цитирования Web of Science Core Collection в расчете на 100 НПР[н]": "citations_wos_5y_per_100_faculty",
    "Количество цитирований публикаций, изданных за последние 5 лет, индексируемых в информационно-аналитической системе научного цитирования Scopus в расчете на 100 НПР[н]": "citations_scopus_5y_per_100_faculty",
    "Количество цитирований публикаций, изданных за последние 5 лет, индексируемых в Российском индексе научного цитирования (далее – РИНЦ) в расчете на 100 НПР[н]": "citations_rinc_5y_per_100_faculty",
    "Число публикаций организации, индексируемых в информационно-аналитической системе научного цитирования Web of Science Core Collection, в расчете на 100 НПР[н]": "publications_wos_per_100_faculty",
    "Число публикаций организации, индексируемых в информационно-аналитической системе научного цитирования Scopus, в расчете на 100 НПР[н]": "publications_scopus_per_100_faculty",
    "Число публикаций организации, индексируемых в информационно-аналитической системе научного цитирования РИНЦ, в расчете на 100 НПР[н]": "publications_rinc_per_100_faculty",
    "Общий объем научно-исследовательских и опытно-конструкторских работ (далее – НИОКР)": "rnd_total_volume",
    "Удельный вес доходов от НИОКР в общих доходах образовательной организации": "rnd_income_share_total",
    "Удельный вес НИОКР, выполненных собственными силами (без привлечения соисполнителей), в общих доходах образовательной организации от НИОКР": "rnd_own_work_share_in_rnd_income",
    "Доходы от НИОКР (за исключением средств бюджетов бюджетной системы Российской Федерации, государственных фондов поддержки науки) в расчете на одного НПР[н]": "rnd_income_per_faculty_excl_budget",
    "Количество лицензионных соглашений": "license_agreements_count",
    "Удельный вес средств, полученных образовательной организацией от использования результатов интеллектуальной деятельности, в общих доходах образовательной организации": "rid_income_share_total",
    "Удельный вес численности НПР без ученой степени – до 30 лет, кандидатов наук – до 35 лет, докторов наук – до 40 лет, в общей численности НПР[н]": "young_faculty_share",
    "Удельный вес научно-педагогических работников, защитивших кандидатские и докторские диссертации за отчетный период в общей численности НПР": "defended_theses_share",
    "Количество научных журналов, в том числе электронных, издаваемых образовательной организацией": "journals_count",
    "Количество полученных грантов за отчетный год в расчете на 100 НПР[н]": "grants_per_100_faculty",

    "Удельный вес численности иностранных студентов (кроме стран Содружества Независимых Государств (далее – СНГ)), обучающихся программам бакалавриата, специалитета, магистратуры, в общей численности студентов (приведенный контингент)": "foreign_students_non_cis_share",
    "Удельный вес численности иностранных студентов из СНГ, обучающихся по программам бакалавриата, специалитета, магистратуры, в общей численности студентов (приведенный контингент)": "foreign_students_cis_share",
    "Удельный вес численности иностранных студентов, завершивших освоение образовательных программ бакалавриата, специалитета, магистратуры, в общей численности студентов (приведенный контингент)": "foreign_graduates_share",
    "Удельный вес численности иностранных студентов (кроме стран СНГ), завершивших освоение образовательных программ бакалавриата, программ специалитета, программ магистратуры, в общей численности студентов (приведенный контингент)": "foreign_graduates_non_cis_share",
    "Удельный вес численности иностранных студентов из стран СНГ, завершивших освоение образовательных программ бакалавриата, программ специалитета, программ магистратуры, в общей численности студентов (приведенный контингент)": "foreign_graduates_cis_share",
    "Удельный вес численности студентов, обучающихся по очной форме обучения по образовательным программам бакалавриата, программам специалитета, программам магистратуры, прошедших обучение за рубежом не менее семестра (триместра), в общей численности студентов, обучающихся по очной форме обучения": "outbound_mobility_semester_share",
    "Численность студентов иностранных образовательных организаций, прошедших обучение в образовательной организации по образовательным по очной форме обучения по образовательным программам бакалавриата, программам специалитета, программам магистратуры, не менее семестра (триместра) в расчете на 100 студентов, обучающихся по очной форме обучения": "inbound_mobility_per_100_students",
    "Удельный вес численности иностранных граждан из числа НПР в общей численности НПР": "foreign_faculty_share",
    "Численность зарубежных ведущих профессоров, преподавателей и исследователей, работающих (работавших) в образовательной организации не менее 1 семестра": "visiting_professors_count",
    "Удельный вес численности иностранных граждан (кроме стран СНГ) из числа аспирантов (адъюнктов), ординаторов, ассистентов-стажеров образовательной организации в общей численности аспирантов (адъюнктов), ординаторов, ассистентов-стажеров": "foreign_postgrad_non_cis_share",
    "Удельный вес численности иностранных граждан из стран СНГ из числа аспирантов (адъюнктов), ординаторов, ассистентов-стажеров образовательной организации в общей численности аспирантов (адъюнктов), ординаторов, ассистентов-стажеров": "foreign_postgrad_cis_share",
    "Объем средств, полученных образовательной организацией от выполнения НИОКР от иностранных граждан и иностранных юридических лиц": "rnd_funds_from_foreign_entities",
    "Объем средств от образовательной деятельности, полученных образовательной организацией от иностранных граждан и иностранных юридических лиц": "edu_funds_from_foreign_entities",

    "Доходы образовательной организации из средств от приносящей доход деятельности в расчете на одного НПР": "income_nonbudget_per_faculty",
    "Доля доходов из средств от приносящей доход деятельности в доходах по всем видам финансового обеспечения (деятельности) образовательной организации": "income_nonbudget_share_total",
    "Отношение средней заработной платы НПР в образовательной организации (из всех источников) к средней заработной плате по экономике региона": "faculty_salary_to_region_avg_ratio",
    "Доходы образовательной организации из всех источников в расчете на численность студентов (приведенный контингент)": "income_per_student",
    "Общая площадь учебно-лабораторных помещений в расчете на одного студента (приведенного контингента),в том числе:": "teaching_lab_area_per_student_total",
    "имеющихся на праве собственности": "teaching_lab_area_owned",
    "закрепленных на праве оперативного управления": "teaching_lab_area_operational",
    "предоставленных в безвозмездное пользование": "teaching_lab_area_free_use",
    "предоставленных в аренду": "teaching_lab_area_rented",
    "Количество персональных компьютеров в расчете на одного студента (приведенного контингента)": "pcs_per_student",
    "Удельный вес стоимости машин и оборудования (не старше 5 лет) в общей стоимости машин и оборудования": "equipment_under_5y_value_share",
    "Количество экземпляров печатных учебных изданий (включая учебники и учебные пособия) из общего количества единиц хранения библиотечного фонда, состоящих на учете, в расчете на одного студента (приведенного контингента)": "printed_textbooks_per_student",
    "Удельный вес НПР, имеющих ученую степень кандидата наук, в общей численности НПР": "faculty_phd_share",
    "Удельный вес НПР имеющих ученую степень доктора наук, в общей численности НПР": "faculty_dsc_share",
    "Удельный вес НПР, имеющих ученую степень кандидата и доктора наук, в общей численности НПР образовательной организации (без совместителей и работающих по договорам гражданско-правового характера)": "faculty_phd_dsc_share",
    "Число НПР, имеющих ученую степень кандидата и доктора наук, в расчете на 100 студентов": "faculty_phd_dsc_per_100_students",
    "Доля штатных работников ППС в общей численности ППС": "faculty_staff_share",

    "2": "section_2",
    "Образовательная деятельность": "section_education",
    "Общая численность студентов, обучающихся по программам бакалавриата, специалитета, магистратуры": "students_total",
    "в том числе:по очной форме обучения": "students_full_time",
    "по очно-заочной (вечерней) форме обучения": "students_part_time_evening",
    "по заочной форме обучения": "students_correspondence",
    "Средний балл ЕГЭ студентов, принятых на обучение по программам бакалавриата и специалитета, по всем формам обучения": "ege_avg_all_forms",
    "Доля обучающихся по программам бакалавриата, специалитета, магистратуры в очной форме": "share_full_time",
    "Доля обучающихся по программам бакалавриата в общей численности обучающихся по программам бакалавриата, специалитета, магистратуры": "share_bachelor_in_total",
    "Доля обучающихся по программам магистратуры в общей численности обучающихся по программам бакалавриата, специалитета, магистратуры": "share_master_in_total",
    "Общая численность слушателей программ дополнительного профессионального образования": "dpo_listeners_total",
    "Общая численность обучающихся по программам среднего профессионального образования": "spo_students_total",
    "Число предприятий, с которыми заключены договоры на подготовку специалистов": "partner_enterprises_count",
    "Число предприятий, являющихся базами практики, с которыми оформлены договорные отношения": "practice_bases_count",

    "Научная деятельность": "section_research",
    "Общий объем средств, поступивших (за отчетный год) от выполнения НИОКР, выполненных собственными силами": "rnd_funds_own_total",
    "Общий объем средств, поступивших (за отчетный год) от выполнения работ, услуг, связанных с научными, научно-техническими, творческими услугами и разработками, выполненных собственными силами": "research_services_funds_own_total",
    "Общее количество публикаций организации в расчете на 100 НПР": "publications_total_per_100_faculty",
    "Количество бизнес-инкубаторов": "incubators_count",
    "Количество технопарков": "technoparks_count",
    "Количество центров коллективного пользования научным оборудованием": "shared_equipment_centers_count",
    "Количество малых предприятий": "small_enterprises_count",
    "Общая численность аспирантов (адъюнктов), интернов, ординаторов, ассистентов-стажеров": "postgrads_total",
    "Доля аспирантов (адъюнктов), интернов, ординаторов, ассистентов-стажеров, обучающихся в очной форме": "postgrads_full_time_share",
    "Общая численность докторантов": "doctoral_students_total",
    "Число диссертационных советов": "dissertation_councils_count",

    "Кадровый потенциал": "section_hr",
    "Общая численность работников образовательной организации (без внешних совместителей и работающих по договорам ГПХ)": "employees_total",
    "Общая численность ППС (без внешних совместителей и работающих по договорам ГПХ)": "faculty_total",
    "Общая численность научных работников (без внешних совместителей и работающих по договорам ГПХ)": "researchers_total",
    "Доля ППС, имеющих ученые степени": "faculty_degree_share",
    "Доля научных работников, имеющих ученые степени": "researchers_degree_share",
    "Доля ППС возрастной категории моложе 65 лет": "faculty_under_65_share",
    "Доля ППС возрастной категории моложе 40 лет": "faculty_under_40_share",
    "Средняя заработная плата ППС (без внешних совместителей и работающих по договорам ГПХ)": "faculty_avg_salary",
    "Средняя заработная плата научных работников (без внешних совместителей и работающих по договорам ГПХ)": "researchers_avg_salary",

    "Международная деятельность": "section_international",
    "Общая численность иностранных студентов, обучающихся по программам бакалавриата, специалитета, магистратуры": "foreign_students_total",
    "Доля иностранных студентов в общей численности студентов, обучающихся по программам бакалавриата, специалитета, магистратуры": "foreign_students_share_total",
    "Общее число образовательных программ высшего образования, реализуемых совместно с зарубежными вузами и ведущих к получению двух дипломов": "double_degree_programs_count",
    "Общая численность обучающихся по очной форме обучения по программам бакалавриата, специалитета, магистратуры, реализуемым совместно с зарубежными вузами и ведущим к получению двух дипломов": "double_degree_students_full_time_total",
    "Общая численность иностранных аспирантов (адъюнктов), интернов, ординаторов, ассистентов-стажеров": "foreign_postgrads_total",
    "Число статей, подготовленных совместно с зарубежными организациями": "intl_coauthored_articles_count",
    "Доходы вуза из иностранных источников на выполнение НИОКР": "rnd_income_foreign_sources",
    "Доходы вуза от образовательной деятельности из иностранных источников": "edu_income_foreign_sources",
    "Количество созданных результатов интеллектуальной деятельности, имеющих правовую охрану за пределами России": "rid_protected_abroad_count",

    "Инфраструктура": "section_infrastructure",
    "Общая площадь зданий (помещений)": "buildings_area_total",
    "Площадь учебно-лабораторных зданий": "teaching_lab_buildings_area",
    "Площадь, предназначенная для научно-исследовательских подразделений": "research_units_area",
    "Площадь общежитий": "dorms_area",
    "Площадь крытых спортивных сооружений": "indoor_sports_area",
    "Доля студентов, не обеспеченных собственным общежитием, в числе студентов, нуждающихся в общежитии": "dorm_shortage_share",
    "Количество персональных компьютеров": "pcs_total",
    "Доля персональных компьютеров, имеющих доступ к Интернету": "pcs_internet_share",
    "Наличие электронной библиотечной системы": "has_e_library_system",

    "Финансово-экономическая деятельность": "section_finance",
    "Доходы вуза из всех источников": "income_total",
    "Доходы вуза из внебюджетных источников": "income_nonbudget",
    "Доля доходов вуза из внебюджетных источников": "income_nonbudget_share",
    "Доля доходов вуза из федерального бюджета": "income_federal_budget_share",
    "Доля доходов вуза из бюджета субъекта РФ и местного бюджета": "income_regional_local_budget_share",
    "Доля доходов вуза от образовательной деятельности в общих доходах вуза": "income_edu_share_total",
    "Доля доходов вуза от научных исследований и разработок в общих доходах вуза": "income_research_share_total",
    "Доля внебюджетных средств в доходах от образовательной деятельности": "nonbudget_share_in_edu_income",
    "Доля внебюджетных средств в доходах от научных исследований и разработок": "nonbudget_share_in_research_income",

    "VUZ": "vuz",
    "Region": "region",
    "Type": "type",
    "Site": "site",
    "ID": "id",
    "year": "year",
}

In [110]:
df = df.rename(columns=col_rename)

In [111]:
df.head()

,ege_avg_budget_full_time,ege_avg_budget_full_time_no_special_rights_no_target_quota,ege_avg_paid_full_time,ege_min_avg_full_time,olympiad_final_winners_admitted_no_exams,school_olympiad_winners_admitted_no_exams,target_admission_count_full_time,target_admission_share_full_time,masters_share_in_total_contingent,postgrad_and_residency_share_in_total_contingent,...,income_edu_share_total,income_research_share_total,nonbudget_share_in_edu_income,nonbudget_share_in_research_income,vuz,region,type,site,id,year
0,0.00,0.00,61.28,48.28,0,0,0,0.0,8.34,8.34,...,80.76,4.42,100.00,100.00,Автономная некоммерческая образовательная орга...,Воронежская область,Частные образовательные организации,http://www.vepi.ru,110170,2022
1,51.69,51.69,51.48,39.26,0,0,0,0.0,0.00,0.00,...,66.01,11.19,34.13,100.00,Автономная некоммерческая образовательная орга...,Воронежская область,Частные образовательные организации,http://www.iict.ru,1996,2022
2,0.00,0.00,0.00,0.00,0,0,0,0.0,0.00,0.00,...,97.58,0.00,100.00,0.00,Автономная некоммерческая образовательная орга...,Курская область,Частные образовательные организации,http://rfei.ru/,2071,2022
3,0.00,0.00,55.70,55.70,0,0,0,0.0,0.00,0.00,...,68.66,1.53,100.00,100.00,Автономная некоммерческая образовательная орга...,Московская область,Частные образовательные организации,https://www.pssi-k.ru/,666667486,2022
4,0.00,0.00,0.00,0.00,0,0,0,0.0,100.00,100.00,...,9.09,85.08,9.77,12.17,Автономная некоммерческая образовательная орга...,г.Москва,Частные образовательные организации,www.skoltech.ru,113493,2022

In [112]:
df = df.drop('id', axis=1)

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 681 entries, 0 to 680
Columns: 132 entries, ege_avg_budget_full_time to year
dtypes: float64(90), int64(38), object(4)
memory usage: 702.4+ KB

Посмотрим на 4 колонки с типом object

In [114]:
df.select_dtypes(include='object')

,vuz,region,type,site
0,Автономная некоммерческая образовательная орга...,Воронежская область,Частные образовательные организации,http://www.vepi.ru
1,Автономная некоммерческая образовательная орга...,Воронежская область,Частные образовательные организации,http://www.iict.ru
2,Автономная некоммерческая образовательная орга...,Курская область,Частные образовательные организации,http://rfei.ru/
3,Автономная некоммерческая образовательная орга...,Московская область,Частные образовательные организации,https://www.pssi-k.ru/
4,Автономная некоммерческая образовательная орга...,г.Москва,Частные образовательные организации,www.skoltech.ru
...,...,...,...,...
676,федеральное государственное бюджетное образова...,Приморский край,Министерство здравоохранения Российской Федерации,https://tgmu.ru/
677,Федеральное государственное бюджетное образова...,Хабаровский край,Министерство науки и высшего образования Росси...,http://pnu.edu.ru
678,федеральное государственное бюджетное образова...,Хабаровский край,Министерство культуры Российской Федерации,http://www.hgiik.ru
679,Частное образовательное учреждение высшего обр...,Республика Бурятия,Частные образовательные организации,bepi-edu.ru
680,Частное образовательное учреждение высшего обр...,Приморский край,Частные образовательные организации,http://www.dvik.info

## Дубликаты

In [115]:
dup_rows = df.duplicated().sum()
dup_rows

0

## Пропуски

In [116]:
miss = (
    df.isna().mean()
      .mul(100)
      .round(2)
      .sort_values(ascending=False)
      .to_frame("missing_%")
)
miss.head(30)

                                     missing_%
publications_wos_per_100_faculty         100.0
citations_wos_5y_per_100_faculty         100.0
section_infrastructure                   100.0
section_hr                               100.0
has_e_library_system                     100.0
publications_scopus_per_100_faculty      100.0
section_finance                          100.0
citations_scopus_5y_per_100_faculty      100.0
section_international                    100.0
section_research                         100.0
section_education                        100.0
research_services_funds_own_total          0.0
dissertation_councils_count                0.0
researchers_avg_salary                     0.0
faculty_avg_salary                         0.0
faculty_under_40_share                     0.0
faculty_under_65_share                     0.0
researchers_degree_share                   0.0
faculty_degree_share                       0.0
dpo_listeners_total                        0.0
researchers_total                          0.0
faculty_total                              0.0
employees_total                            0.0
spo_students_total                         0.0
doctoral_students_total                    0.0
publications_total_per_100_faculty         0.0
postgrads_full_time_share                  0.0
postgrads_total                            0.0
partner_enterprises_count                  0.0
practice_bases_count                       0.0

Присутствуют пропуски и они 100% можно просто убрать эти столбцы

In [117]:
df = df.drop(['publications_scopus_per_100_faculty', 'section_infrastructure', 'section_finance', 'publications_wos_per_100_faculty', 'section_hr', 'citations_scopus_5y_per_100_faculty', 'citations_wos_5y_per_100_faculty', 'has_e_library_system', 'section_education', 'section_research', 'section_international'], axis=1)

## Константные / почти константные колонки

In [118]:
nunique = df.nunique(dropna=False).sort_values()
const_cols = nunique[nunique <= 1]
print("Константные колонки:", len(const_cols))
if len(const_cols):
    for col in const_cols.index:
        print(f"\nКолонка: {col}")
        print(f"Уникальные значения: {df[col].unique()}")
        print(f"Количество NaN: {df[col].isna().sum()}")

Константные колонки: 2

Колонка: year
Уникальные значения: [2022]
Количество NaN: 0

Колонка: section_2
Уникальные значения: [4]
Количество NaN: 0

In [119]:
near_const = []
for c in df.columns:
    vc = df[c].value_counts(dropna=False)
    if len(vc) == 0:
        continue
    if (vc.iloc[0] / len(df)) >= 0.99:
        near_const.append((c, float(vc.iloc[0] / len(df))))
near_const = sorted(near_const, key=lambda x: x[1], reverse=True)
print("Почти константные признаки:", len(near_const))
pd.DataFrame(near_const, columns=["col", "top_share"]).head(30)

Почти константные признаки: 2

         col  top_share
0  section_2        1.0
1       year        1.0

Удалим данные константные колонки

In [120]:
df = df.drop(['section_2', 'year'], axis=1)

In [121]:
df.shape

(681, 119)

## Описательная статистика

### Числовые

In [122]:
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()

In [123]:
desc = df[num_cols].describe(percentiles=[.01, .05, .5, .95, .99]).T
desc.sort_values("std", ascending=False).head(30)

,count,mean,std,min,1%,5%,50%,95%,99%,max
income_total,681.0,1.544827e+06,3.053261e+06,62.00,4515.200,15500.00,689929.50,6024791.20,1.373365e+07,38320205.20
income_nonbudget,681.0,6.509417e+05,1.426923e+06,0.00,2751.520,10302.50,211070.10,2608756.30,6.858942e+06,15899410.50
research_services_funds_own_total,681.0,1.713239e+05,5.405918e+05,0.00,0.000,0.00,26708.80,858078.40,2.341808e+06,7566786.00
rnd_total_volume,681.0,1.710789e+05,5.395120e+05,0.00,0.000,0.00,27722.60,810576.00,2.374154e+06,7752989.00
rnd_funds_own_total,681.0,1.595528e+05,5.135417e+05,0.00,0.000,0.00,25058.20,783076.00,2.222736e+06,7566786.00
buildings_area_total,681.0,8.422733e+04,1.249793e+05,0.00,512.200,1666.00,52823.00,252815.00,5.751948e+05,1662182.00
edu_funds_from_foreign_entities,681.0,3.362995e+04,1.100230e+05,0.00,0.000,0.00,1794.30,167843.90,5.577539e+05,1717091.10
edu_income_foreign_sources,681.0,3.362995e+04,1.100230e+05,0.00,0.000,0.00,1794.30,167843.90,5.577539e+05,1717091.10
teaching_lab_buildings_area,681.0,5.439200e+04,7.486633e+04,0.00,512.200,1554.00,35036.00,166366.00,3.156436e+05,987056.00
dorms_area,681.0,2.137683e+04,3.274089e+04,0.00,0.000,0.00,12925.00,71675.00,1.403678e+05,359113.00
rnd_funds_from_foreign_entities,681.0,2.133162e+03,1.149291e+04,0.00,0.000,0.00,0.00,8982.10,5.086132e+04,205070.60
rnd_income_foreign_sources,681.0,2.133162e+03,1.149291e+04,0.00,0.000,0.00,0.00,8982.10,5.086132e+04,205070.60
research_units_area,681.0,2.304098e+03,7.665781e+03,0.00,0.000,0.00,325.00,10099.00,2.806820e+04,126924.00
students_total,681.0,5.268489e+03,6.018055e+03,4.00,15.600,72.00,3612.00,17300.00,2.881900e+04,37926.00
citations_rinc_5y_per_100_faculty,681.0,2.394172e+03,5.993285e+03,0.00,0.000,0.00,926.84,8621.36,2.717562e+04,84864.63
dpo_listeners_total,681.0,2.811463e+03,5.037779e+03,0.00,0.000,0.00,1028.00,11037.00,2.468880e+04,55090.00
students_full_time,681.0,3.394389e+03,4.643640e+03,0.00,0.000,3.00,1913.00,11620.00,2.262600e+04,36854.00
indoor_sports_area,681.0,2.888756e+03,4.637911e+03,0.00,0.000,0.00,1248.00,11330.00,2.275720e+04,41999.00
income_nonbudget_per_faculty,681.0,2.032821e+03,2.473910e+03,0.00,111.756,325.74,1345.17,5512.74,1.032179e+04,42597.89
pcs_total,681.0,1.465555e+03,2.122815e+03,0.00,19.000,46.00,804.00,4860.00,8.927800e+03,24767.00
students_correspondence,681.0,1.570266e+03,1.993023e+03,0.00,0.000,0.00,842.00,5263.00,8.005600e+03,18386.00
printed_textbooks_per_student,681.0,3.540040e+02,1.938887e+03,0.00,0.000,8.98,144.08,748.15,2.415852e+03,43780.00
income_per_student,681.0,6.521593e+02,1.872494e+03,13.61,122.892,181.65,334.37,1556.43,5.386648e+03,35650.00
employees_total,681.0,7.617651e+02,1.205293e+03,2.00,7.000,22.00,423.00,2577.00,5.216400e+03,18423.00
spo_students_total,681.0,5.782731e+02,1.064316e+03,0.00,0.000,0.00,1.00,2484.00,4.399800e+03,12675.00
foreign_students_total,681.0,4.506828e+02,8.153751e+02,0.00,0.000,1.00,153.00,1842.00,4.178800e+03,7658.00
students_part_time_evening,681.0,3.038341e+02,6.521445e+02,0.00,0.000,0.00,82.00,1237.00,2.948000e+03,7902.00
practice_bases_count,681.0,3.432952e+02,5.934989e+02,0.00,0.000,0.00,98.00,1380.00,2.412000e+03,5508.00
rnd_income_per_faculty_excl_budget,681.0,2.399890e+02,5.582137e+02,0.00,0.000,0.00,110.95,777.80,2.573868e+03,9802.27
publications_total_per_100_faculty,681.0,4.953286e+02,5.188304e+02,0.00,0.000,52.10,369.67,1292.10,2.391668e+03,6469.34

Выводы:
- Почти все финансовые и инфраструктурные показатели имеют среднее значительно выше медианы, очень большие 95–99 перцентили, огромной разрыв между min и max
- printed_textbooks_per_student – максимум в 300 раз больше медианы
- citations_rinc_5y_per_100_faculty – очень сильная асимметрия, но это возможная ситуация
- income_total vs income_nonbudget – в среднем внебюджет ≈ 42% от total, но распределение неравномерное
- R&D показатели – более 50% вузов не имеют иностранных R&D доходов (медиана = 0)
- студенты – есть крупные университеты, но значительная часть — средние и малые.
- иностранные студенты – часть вузов вообще не работает с иностранцами
- инфрастуктура – площадь вузов отличается более чем в 30 раз от медианы, 50% вузов имеют общежития
- income_per_student, rnd_income_per_faculty_excl_budget, income_nonbudget_per_faculty – показатели имеют сильную асимметрию